import request from './request'

export const getBanner= () => request({url:'/banner',method:'get'})
export const getHotNav = ()=>request({url:'/playlist/hot',method:"get"})
export const getHotList = (data)=>request({url:'/top/playlist',params:data,method:"get"})
export const getAlbumList = (data)=>request({url:'/album/new',method:"get",params:data})
export const getPlayList = (id,s)=>request({url:`/playlist/detail?id=${id}&s=${s}`})
export const getNewMvList = (data)=>request({url:`/mv/all`,method:'get',params:data})
export const getStationList = (limit)=>request({url:`/dj/hot?limit=${limit}`,method:'get'})
export const getArtistList = (limit)=>request({url:`/top/artists?limit=${limit}`,method:'get'})
export const getTopList=()=>request({url:'/toplist/detail',method:'get'})
export const getCatList = ()=>request({url:'/playlist/catlist',method:"get"})
export const getRelatedList=(id)=>request({url:`/related/playlist?id=${id}`})
export const getSimiSong=(id)=>request({url:`/simi/song?id=${id}`})
export const getSimiPlay=(id)=>request({url:`/simi/playlist?id=${id}`})
export const getSongDetail=(id)=>request({url:`/song/detail?ids=${id}`})
export const getLyric=(id)=>request({url:`/lyric?id=${id}`})
export const getMvDetail=(id)=>request({url:`/mv/detail?mvid=${id}`,method:'get'})
export const getSimiMv=(id)=>request({url:`/simi/mv?mvid=${id}`,method:'get'})
export const getMvUrl=(id)=>request({url:`/mv/url?id=${id}`,method:'get'})
export const getSongUrl=(id)=>request({url:`/song/url?id=${id}`,method:'get'})